# Generated by Django 4.2.7 on 2024-09-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('slug', models.SlugField(editable=False)),
                ('image_1', models.FileField(upload_to='products/images', verbose_name='imagen 1')),
                ('image_2', models.FileField(blank=True, upload_to='products/images', verbose_name='imagen 2')),
                ('image_3', models.FileField(blank=True, upload_to='products/images', verbose_name='imagen 3')),
                ('characteristic_1', models.CharField(blank=True, max_length=100, verbose_name='característica 1')),
                ('characteristic_2', models.CharField(blank=True, max_length=100, verbose_name='característica 2')),
                ('characteristic_3', models.CharField(blank=True, max_length=100, verbose_name='característica 3')),
                ('isFeatured', models.BooleanField(default=False, verbose_name='producto destacado?')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='marca')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
